#----------------------------------------------------------------------
# This file was generated by /Users/fzdp/Projects/wxpython-projects/wxpython-note-tutorial/utils/encode_bitmap_util.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

tool_code_block_active = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAABRUlEQVQ4T+2UP0vDUBTFz0kW'
    b'dXCzm7jr5OCY1ExOiotpF4cuDtJYFOmqfgDBJE6dREQTskTcbQ36FVxEcFY/gBTSJ69QCflD'
    b'VDr2je/d83vvvnvuJca8WMRrduur8uzc8HqjGLlHNX539eC5SJcBtiJzDeSpEFiSIhKmrfnB'
    b'3oN5DPJI7gkgVGPunxneWxqcAUohyQVb9xt5rzh82q70435HgKGrexelQCuqdUXMk2SqaZG8'
    b'VJBVV/eNCRA/Rdm5W5+Zmp1uy0oKDCquHnwUWaP1WN8QA3ErwEa6MEOgFW0tEsoVgXkQu9Im'
    b'ZX5vRuamAlyCfHU0f3kUnwEy5kqev/IqDeIgFyiDkyl/xcpcx7j5/HfKSeHEh7nf+KfW++1w'
    b'IHlva55T2suF4yuqWQCGAAKhEGrbqV6/lAKTw3QsA7asQ8rOvwFOn+AVcnBwGQAAAABJRU5E'
    b'rkJggg==')

#----------------------------------------------------------------------
empty_note = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAG3klEQVR4Xt1bTXYTORCuknjP'
    b'2U04AeEEE9bzMMkJCAto7wgHiGNOQHICjDkAyS6eWRBOEKd5rLFPMM4JJtlNYLprXvWPre5W'
    b't6RO27HRCmKpuupTqf5UQmh4dC+9Q0DoAcBWFWkCOJcBvu3vnk0bZsGJHDrNNkw+9L1PBLDv'
    b'QPNayHC3/8dfY4c1jU5tDIADv7OPQJ803F0B4CjWCHqm+X06aA8fNyqVA7ECAL1vL7fDEJ8T'
    b'4TYAbOZoXUug0377z/P8N7p+Z1QUEE8H7bOZRkS0A8Fg/KauF4i7/adn/PfMOPS99yEA85EZ'
    b'iDSCEKYi/PGlv3t+7SBvYeoMgN7F3mYgW58QYM9AcDJoDwtMdX2PcutuRHC7lWewe9k5AqR3'
    b'mbmEx4NnZ0fq33pfOzsh0YWBl2sB9Ea3IbagRACw8KFoXQAW0c4LRYC9j+2zk6IG5AHAy0H7'
    b'bCc/TyuYDgDmSW6clxybLH6Ab3Q82YAQAdD1OycA9DpZMBGIPZ1KVhHUaID2bGtthQaAqm/F'
    b'G7bRUzVJBPi4jkfBiJhs/ZMKr1NvGyQ1AAABvP3YHvbT9cm3vhdcpCMAM3r+q70Q8HP0f4QP'
    b'g6dDdr9OA9UdEUAv6p4nHQDMCft7JDoHAVtAyAzmDStATQBi7fXYhf4OALW8CapGqa4aJYzk'
    b'jaD9TtwJgPnxHbSHzm49A4AtgQP/ZcGfI0TurdZAgJMQwoxhlYG8sjnT6gba8q8y6QQA+2WC'
    b'KMxd1pgKGb6oihSXBkBFpLdoMCrP9tIA6PoeR3/PFy2tjr6Q4ZMyLagDQBKRPgKkbesj0P3q'
    b'9YHg8F4ACG4floW8LgB0L1+9JsR9BJgFaNYA9C46W6EkdjmZOH7hgBj8uw0AvTheeK9J0W+s'
    b'AWBBk3xhHwmLvnwBSAgBI1NEWgUAb1ogifObQkges4uXTgAsQMY7kywDIDHavOsVm/ULAsBa'
    b'SrLF7tpcmCE8/qU0QAS3Dy2z2kjzOFdZewCSBCuOQgnIIqWfHTsuxKw9AJFx/tqJjJxFASVj'
    b'c1hjrAFIztY7LlFhXKZamCcggJEAmKIMP5gKpklQk1aOXHi6GbSHm9YAaEtZd7bhJgL6qlK6'
    b'KolNuL7gIniyPKZtDUB01h60jiAqlmqruyZpXH6fAOBYyKBfpgEOZTz9d5MU3BoAF+6XMbd7'
    b'6X13MXh5ntLiz1oCUOMCprAnaYK1dgAc+F4PATjCKxs3sYuvtAuRAYyCYZtkYhkqbfMNy7uC'
    b'L+a0fW5c1waAJOD5u3JnCY8Bo/J+5cWsWoRdGwAOfO9z9a0VngLBtHDrpFEttfq9FgBYnPuJ'
    b'kOF+GAiOCYyDI8C0wLLyAFgEOzciwO1QwpFyu1UFQuZuc+UBOPC9i/KCBgAnNG55QPbG2hoA'
    b'jrmDQLyzuD02qqDVBIIxIowqy/BJNGcCSf0e5S5SrQG4z6KoHrDYlTmW66Pjol64WAPATCTG'
    b'aAdgGTVB4kCF7/x0I+o9iFRftoqXrboVhMci/Lefry47AWClug1MMvn81I3ZZah4KgI4CmTw'
    b'SKLEfJF1JQGoFCwpkyfegQOjsjFBAK4TbFLc9bKpu/1eOQAMuz9zYebAqIiL6v/TX1cOgKrd'
    b'TzM4y5wgh4C+uLJ6APgeq3Uxlld6COrUAvLubyU1ILnCilteskNVfVM6XOo1dPeLK6UBZTfQ'
    b'M9WP+5mqM8ISF5hvw1s5Dcg1a83FUFW/3g311aA9LE2PnTUgvnAMHjXg7jMkEHEHCDPNkgBw'
    b'JYLbbVbdpPxtle2phMu6UJ01ILG83AtcXWxoEBmVeZd4f8aCRfOVtQZY5OQNis6k5llbhXEs'
    b'++YVEJ6UnXt1kTUAvChSw/+kqZe4HhBI3H2SXnDM+oxLmys1noIATqQMR6bbpNoA1JPMvCof'
    b'2KgdpjbxftSMiTQmopEMfk5cOsidNMAsSr0ZOfc38/kW8b7e5yPumTpLnI1gPdHMq/JC3tHw'
    b'TUSAezYNlloA7tIqaxZVPyPbqT43fI6Fjvtvlq4DQG7384bPNuKr1d4/04BMBEYwHjwbPqkj'
    b'TJ01qoFTDV9iFLkllxsfytryrgjwqO5DiRkA/I+MGhKMhcC3tkakjuDpmq7v8TsFdn3aZziR'
    b'673obMGDOPgKQ9gRGI5B0tTF1VXxOH8yI1vcZ1NWg6slZ1kKysQy7xRKHk3V+qjjosyjqVBu'
    b'9C0vF6w/UwbC3PVl6/TWhBuaqH82x9EeRmrXSNwvZNBTVVaxO9qXZQ3JZkXG+YWFFVXDpFT9'
    b'82+KmqDtSuNeAEjUf6vuAy1XIY1GsEmCNrTY+gvEF8vwNCZ+lq4B8fnf6KtPak1MLvL35QPw'
    b'7eU2/Pg5dcnYFgnA/+XleWciLG41AAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
tool_bold = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAA2ElEQVQ4T73UMU4CURSF4W9W'
    b'4BZgD9aKBQswakUDC2AXlBYUlCRS2NrYWGpnRaisIaGgggQb6SAvGQsHZpI3vnCT173755xz'
    b'b24mcWWJec4GfC9RPsYbNmXOyhTuK6KYoY31qT9VwA/cFJoeMMQn7lMAA+MV17hIBXxGB5eY'
    b'FqGxllt4wTeadRQWewIwVA+TFMAGwlvgCsv/Wg79XTzlCoPSPxWb4W/zCrtTOdYFznPy0WBi'
    b'gSG/OzxihH6M5apDFPbvNmYoZcfhB18YYBuzNrXP5NnuYW2FB/BDMhX9SGtpAAAAAElFTkSu'
    b'QmCC')

#----------------------------------------------------------------------
tool_color = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAyElEQVQ4T7XTMU5CQRSF4Y/O'
    b'UEOhRLcBa6DAVlpNtBG2IGxBaDDRVlssWANuQyMUUBs7yJgHMRMGXvLC7SaT888999wpKVil'
    b'gnpHBayi7nY+lurgHJ8R4AJfseUUoINHNDPBBF0M8gKmqLOdUbDzgUYeQAULPOEuE4xwiyqW'
    b'/yG7LFzhNRFvG2+HAM+4TgBecLMPUM4m/YtaBPnGCUJCP5u72EILY/TRiwDh/IBLvKcAIaZ7'
    b'nGEeAU4xwxAh5r866irn+meFO1gDb9MdEeTY7SUAAAAASUVORK5CYII=')

#----------------------------------------------------------------------
tool_bold_active = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAABKklEQVQ4T2NkoDJgpLJ5DPQx'
    b'MPdQ+H6sLv/PMIeF9d/2fqvV73D5DKsL8w6F/8cTFOf/srO7TjVf9BabGpwG/mdgODDZbqUj'
    b'sqb8w+Gh/xkYJjD8Zzg+yW5lCMUGggzIOxy+ieE/g/0ku5X81DHwUPgSBgaGaAbGfyaTbFef'
    b'RTeUJC/n7I9wYGL+v5aBgeHTJLuViiS7EIvtDiCx/wyMiZPtViyghoEKDAwMIPyA5T+jXZ/9'
    b'iscUeRmkOfdQRAIjw//5jAwMCybarUyk2EBwTB8Kf87AwPADWziSFCkw1+QdCr8PYlNsYMH+'
    b'CIW/TP+CGRkZe/4zMEyZbLcyl2gvEyiFzrL8ZwwkOlJwFQ5MjAzf////f/XHz/8ts1xXfyQ6'
    b'2VBSRtKnPKTEhQDPhJMVPj6tVQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
tool_code_block = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAA5UlEQVQ4T+3UoU5DQRCF4a8W'
    b'X1yDB4VAUxSOVOGxTRAgats+QA0SRQgOU14AeIqahgQNPASZZG+yNHtvb0NlV+7O/Luz58x0'
    b'bHl1Gnj9dPaexcTeFxZ1eSXgOWY4SkmXeMYE47Q3xw0+V8ElYCQe4KrmFfu4R0Af2gDfMEVe'
    b'6mpeXHqKsx1QLsoeRknJ+PjvBktd4CUJ90eYCniIJ/QwTDZZZ/kBHvGB4yq4BDwp+atAD6Vv'
    b'64ARn5fcxc9/Ss5zdz4s/uRGrdd2OLzirk0v142v6wwQkyaaYNkGWMVsbcCu65DG819S2j4V'
    b'NHS3cgAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
add_note = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACnUlEQVRYR82XPWgTYRjHf88p'
    b'WOtHEesoVQdBnUQRBZssKrhUVNILgg4OgkJOBycVrKBODpqAgoODg/QaFexSqA4mERTxY1LB'
    b'Qa2OVqTV1gp6j9zF60eSSy5fpDcF7nn+zy/v+97z/F8h5HP0Sc+ypX/ad6mhpsB6hU4RVrrp'
    b'qnwTGFV4L47YPxdOPrq1c/BHGGmpFHQqY25QIeFAXGBFpXgPCL4b0C9K6mrUflcupyyAlTEv'
    b'YpBAWR6mcFGMMI5DKhm1zwXlBwJYGTOL0F1T4cIkJZeM2pFSWiUBrIz5FaGzIcV9EWU0GbVX'
    b'FWoWAVhZ8yOwpqHFZ8Q+JSP22tnacwASWXNAINak4p6sQjoVsXv9GtMA3oETzjaz+LS2csk/'
    b'mB6A+6k5Bs+qPO3DiHMm/7eMy8Ce0PDCuOGw3f1EPYCTWfO6wvHQAvnucyEZHehzf1qZ3j5E'
    b'zleTL3DjWsQ+IccexjraFhkjQEc1AvUCAGNTv50usXLxw6jerqp4A1bAqydyRKyseRc42BIA'
    b'uOcCvAI2twjgtSSy5meB1YG9WhhSR5+Xej/nEJYIEEO2qbI3SFvhi1g5cwKlPTjI2ZSKpN9W'
    b'vUJAIhvbKBhvAnOFyYoAiLM12Z1+WQuAlYttQY0XZQEqbQEwjOrTWrYAkR3lGlR+C+bBIewX'
    b'MKte4jo74f/BZIv1OL4fQ++3AgBHDohrNpc4i0fC+r2ZiVbfLHB944Txq6v1w6jWcSzCkKPO'
    b'aTffEONKuYZTtL2F4zg/UltoSHzChjrh4NY6xyEXm9JmOGIfpoQzLm3Lm+OMixyxZwmCVqqR'
    b'DrnQCc+uOX+vZj6lfzlVOFSFbxwTuFP35XT2UnnmtW1BD6r7gHWlrufAB0QeTE39Hby5Oz0W'
    b'pr3/A0+nSshaPpsgAAAAAElFTkSuQmCC')

#----------------------------------------------------------------------
tool_bg_color = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAA7klEQVQ4T73UsUoDQRDG8d81'
    b'1jZiaRHwDewVQYhVGgVJlcZOMIWClWlTaGXtA4hgp53xKWLhA1jYp00YyMGyitzljky3u7P/'
    b'nW/32ym0HEXLPGsBPmGrYuU/OE1z8wpf0a0IK9PecFwOcuAE+38Az/GFWM/jAwd1gXHwBqbo'
    b'ZMTawHccoo9t3DUFnuAbVzjDrCkw5N5jiB08Yy+B1pIcm6PCNAZ4XBUYd7eJiwQQLzpfFRhy'
    b'rzFOALt4wNFyrpLkSArfhf9e0EuAN/jE5dKzlYGlWXOzl59hhFv8C2z964WyVptDzb7wO30t'
    b'/bBRlQvBFDQV9vqmHQAAAABJRU5ErkJggg==')

#----------------------------------------------------------------------
tool_background = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAA2UlEQVQ4T62U0Q3CMAxEX9eB'
    b'CWABxACwDmUd+C8jIAag64DOiisTpZREWMpHneTZunPa8afoAmcD7IAXcA75FXAAdPYJXMNe'
    b'D2jZpmIPDOnQMYNcgDWgfIQorwKWd5CoqlwLEdjuRJC1mELQpU4mSARFyashJVALRDpNGgna'
    b'CpERvWvUCpGOGpUJJKFPXyz+EDbZLojmSq6N0bV82HxOFiFRbBMsWFcFmbO/GlICtUDsvcVH'
    b'2wLRnbHk2k/CJi298Ba4x45ywfWtYVN4ZffD3+UDuM2J3fSrewMT7lsTKY2gZwAAAABJRU5E'
    b'rkJggg==')

#----------------------------------------------------------------------
sort = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAApklEQVQ4T7WTMQ6DMAxFH4fg'
    b'CizsXeEAnXsd6Fk6siLWhpMVGdlSFIoSJJONxH75/vxUOK3KicNtoB/wBkZV2hcqDqmiFCTA'
    b'IQPbL86B3BQVTsbB7HQ0N5B41P2hrdEP2Y9zHrmB3Ea7BGqBWju+Gsig32J+PL7tHy6wogfw'
    b'ARqtmICXhtFSHif+FCQHEr4FmBVie3FTVpEVPxVU7I0V3vb6Lyuxhg0QPSYTZyR0cQAAAABJ'
    b'RU5ErkJggg==')

#----------------------------------------------------------------------
more = PyEmbeddedImage(
    b'iVBORw0KGgoAAAANSUhEUgAAABIAAAASCAYAAABWzo5XAAAAjklEQVQ4T+3RsQ3CQAyF4S8D'
    b'ME0YAMagyAJUSDAGKB0jMAE9DAC7IDEA6CQHRUB0zaWLq9Pz+en3c6VQVYV8TEb5JEfLaIYG'
    b'xx7DIt7XnrbGCY9O+yZ6RWOHA2rcQpvjji32oX3mc0aJ5hJDSySqFpuc0b/VElWqRNPVCmc8'
    b'h1bLn2fgx2hXm4h+EygW9hshbxIT2SPrWgAAAABJRU5ErkJggg==')

